name: apos
description: "mini POS"
publish_to: 'none'
version: 0.2.7

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  cloud_firestore: ^5.1.0
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  loader_overlay: ^4.0.0
  loading_animation_widget: ^1.2.1
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  equatable: ^2.0.5
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
