// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdmmH9ACYgW7JXk5A2sdUn-vmdxwriBE8',
    appId: '1:195842948453:web:8f0c1127ffd4953504b58c',
    messagingSenderId: '195842948453',
    projectId: 'apos-d1548',
    authDomain: 'apos-d1548.firebaseapp.com',
    databaseURL: 'https://apos-d1548-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apos-d1548.appspot.com',
    measurementId: 'G-2TTB22MG2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChu_2Ym1RR2QvS2BbIXmRSiiB8mrewWkE',
    appId: '1:195842948453:android:3160aaa4c01f351904b58c',
    messagingSenderId: '195842948453',
    projectId: 'apos-d1548',
    databaseURL: 'https://apos-d1548-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apos-d1548.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXCzL6UuC_VRC_a05KHEuE0B0fARUM7yI',
    appId: '1:195842948453:ios:39a9611e098d6d6304b58c',
    messagingSenderId: '195842948453',
    projectId: 'apos-d1548',
    databaseURL: 'https://apos-d1548-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apos-d1548.appspot.com',
    iosBundleId: 'com.example.apos',
  );
}
